# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hist CPP
#'
#' @export
#' @importFrom Rcpp evalCpp
#' @useDynLib spAirPol
#' @return bounded numeric vector
hist_exp_cpp <- function(y, lambda, lag) {
    .Call('_stAirPol_hist_exp_cpp', PACKAGE = 'stAirPol', y, lambda, lag)
}

hist_exp_anti_cpp <- function(y, lambda, lag, scale, border) {
    .Call('_stAirPol_hist_exp_anti_cpp', PACKAGE = 'stAirPol', y, lambda, lag, scale, border)
}

